/**
 * Represents a single action item extracted by the AI.
 * Designed to map directly to Azure DevOps work item fields.
 */
export interface ActionItem {
  title: string;
  description: string;
  type: 'User Story' | 'Task' | 'Bug';
}

/**
 * The structured summary generated by Azure OpenAI.
 */
export interface MeetingSummary {
  key_points: string[];
  decisions: string[];
  action_items: ActionItem[];
}

/**
 * Represents a single message in the Q&A chat.
 */
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  type?: string;
  data?: any[];
}

/**
 * The root model for a Meeting session in LUMI.
 */
export interface MeetingDetails {
  meeting_id: string;
  transcript: string;
  summary: MeetingSummary | null;
  qa_history: ChatMessage[];
}